### ISSUE TITLE
Scaling etcd 3.2 stable on Bionic fails

### ISSUE THREAD

**Issue by jbrisko** [juju-solutions/layer-etcd#136]
Hey guys!

I am just digging into an issue and want to see if it's known and if resolution is coming. I am running Juju 2.4 on Bionic. I have deployed etcd charm #96 and recently upgraded it to latest stable #126. My nodes deploy fine, but if I try to add a new node into the cluster, that node cannot register. It keeps getting a unexpected status code 404 in the register_node_with_leader function of etcd.py. It seems to me through my debugging, that the logic in the etcd.py and etcdctl.py files are tied to API v2 for etcd and not working properly for v3 clusters. Thanks for all of your work and help on this project!

**Comment by ktsakalozos** [comment]
Hi @jbrisko,

Thank you for reaching out. Our charm should not be tied to the v2 API. However, if you have a v2 deployment and you upgrade you will still be using the v2 API for compatibility reasons (see also Known limitations at https://jujucharms.com/etcd/126). Can you share a stack trace of the error you are seeing and a way to reproduce it.

Thank you for your time.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809383.
