### ISSUE TITLE
etcdctl snap deployed to a xenial-lxd deployment being denied file_lock in apparmor

### ISSUE THREAD

**Issue by afreiberger** [juju-solutions/layer-etcd#139]
Every 5 minutes (update-status hook) the etcd charm is calling etcdctl which is causing 4 entries in the kernel logs for apparmor denials

[Wed Sep 26 15:46:31 2018] audit: type=1400 audit(1537976803.563:59951): apparmor="DENIED" operation="file_lock" namespace="root//lxd-juju-7e2a4a-15-lxd-2_<var-lib-lxd>" profile="/snap/core/5328/usr/lib/snapd/snap-confine" name="/dev/null" pid=1907424 comm="etcdctl" requested_mask="k" denied_mask="k" fsuid=100000 ouid=0
[Wed Sep 26 15:46:32 2018] audit: type=1400 audit(1537976804.507:59952): apparmor="DENIED" operation="file_lock" namespace="root//lxd-juju-7e2a4a-15-lxd-2_<var-lib-lxd>" profile="/snap/core/5328/usr/lib/snapd/snap-confine" name="/dev/null" pid=1907909 comm="etcdctl" requested_mask="k" denied_mask="k" fsuid=100000 ouid=0
[Wed Sep 26 15:46:33 2018] audit: type=1400 audit(1537976805.331:59953): apparmor="DENIED" operation="file_lock" namespace="root//lxd-juju-7e2a4a-15-lxd-2_<var-lib-lxd>" profile="/snap/core/5328/usr/lib/snapd/snap-confine" name="/dev/null" pid=1908489 comm="etcdctl" requested_mask="k" denied_mask="k" fsuid=100000 ouid=0
[Wed Sep 26 15:46:33 2018] audit: type=1400 audit(1537976805.427:59954): apparmor="DENIED" operation="file_lock" namespace="root//lxd-juju-7e2a4a-15-lxd-2_<var-lib-lxd>" profile="/snap/core/5328/usr/lib/snapd/snap-confine" name="/dev/null" pid=1908548 comm="etcdctl" requested_mask="k" denied_mask="k" fsuid=100000 ouid=0

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809385.
