### ISSUE TITLE
Request a new certificate for etcd

### ISSUE THREAD

**Issue by Coolfeather2** [juju-solutions/layer-etcd#141]
Currently etcd is connected to easyrsa and got the certificates at startup, now the IP has changed it needs a new certificate

How would I force etcd to request a new certificate?

**Comment by Coolfeather2** [comment]
```
failed to check the health of member 1edf4e6f9264548 on https://192.168.1.73:2379: Get https://192.168.1.73:2379/health: x509: certificate is valid for 192.168.1.147, not 192.168.1.73
```

**Comment by hyperbolic2346** [comment]
As a general note, having your cluster change IP is not a good thing and I wouldn't suggest it.

That said, you can kick this off a couple of ways. A charm upgrade would trigger it and that might be the easiest. If not that, you could clear some flags to make it happen again. Removing the states etcd.tls.secured and etcd.ssl.placed should kick off a new request for a certificate. Something like `juju run --unit etcd/2 -- charms.reactive remove_state etcd.ssl.placed` and `juju run --unit etcd/2 -- charms.reactive remove_state etcd.tls.secured` should do it.

**Comment by Coolfeather2** [comment]
I'll try isolating it to a custom DHCP scope
