### ISSUE TITLE
snapshot action should pick a sane keys-version

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/layer-etcd#143]
When snapshotting/restoring etcd, it's important that you get the version right.  We don't advertise this in the readme, but the `snapshot` action has a `keys-version` that should match the deployed version:

https://github.com/juju-solutions/layer-etcd/blob/master/actions.yaml#L22

I think we should update the action to default to an `auto` value that will set `v2` or `v3` based on the current channel configured in the charm:

https://github.com/juju-solutions/layer-etcd/blob/master/config.yaml#L12

```
if keys-version == auto:
    if channel startswith 2:
        keys-version=v2
    else:
        keys-version=v3
```

We should also update the readme to talk about this setting.

**Comment by evilnick** [comment]
This is a good idea. I think it would also help to include the version in the filename, e.g.
 
       etcd-v2-snapshot-2018-09-26-18.04.02.tar.gz

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809388.
