### ISSUE TITLE
Warning notice from docker about the image origin for etcd

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/layer-etcd#41]
When installing k8s + etcd: 

```
k8s: gcr.io/google_containers/etcd: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```

It seems to be related to the API version (v1). If the etcd is not republished with a v2 api this image might fail pulling unless a tag is added in the docker pull command.

**Comment by chuckbutler** [comment]
This issue appears to stem in either layer-flannel or kubernetes/kubernetes. 

Marking as invalid until the bug gets linked in its appropriate location.
