### ISSUE TITLE
The etcd charm pulls easy-rsa from github.com

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-etcd#45]
The tls layer pulls easy-rsa from github.com we should resolve this so we can deploy in network limited environments.

**Comment by mbruzek** [comment]
The tls code was not replacing configuration values correctly when I deployed this version with resources. 

We will have to include another way to add resources to this layer and have them added by default.

**Comment by chuckbutler** [comment]
Linking against #50
