### ISSUE TITLE
Fix travis failures in etcd

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-etcd#66]
The travis.yml calls tox and the tox tests are broken. We should fix this.

**Comment by chuckbutler** [comment]
I'm +1 to this notion. 

The charm will have to be built and the tests will need to be executed against the assembled charm unless there's a way to stub out LAYER_OPTIONS. Thats the root of the failure from the change set.

**Comment by mbruzek** [comment]
@chuckbutler I see that you reopened this. I see some commits after this merge, but I don't see a PR. Do we need to do something else here?

**Comment by chuckbutler** [comment]
I'm not really happy with the implementation. it works, but its a gigantic bandaid covering up a larger issue which is how do you test isolated layers. We can close this and open a new issue to track fixing the hack.
