### ISSUE TITLE
Support for TLS secured etcd connections configured via Juju Charms

### ISSUE THREAD

**Issue by francisco-hernandez-canonical** [juju-solutions/layer-etcd#7]
A charm deployment of Calico uses Canonical’s etcd charm. 
In order to support TLS authentication of etcd connections, Metaswitch will need an updated etcd charm which includes the relevant configuration options to enable TLS mode for etcd (both as a etcd master and proxy) and a mechanism for deploying SSL certificates issued by Customers Link’s certificate authority.  
Metaswitch will update the relevant Calico charms to use thesame mechanism to configure TLS and deploy certificates for Calico’s etcd connections

**Comment by chuckbutler** [comment]
#12 is the beginning of this work, and its nearly complete.

**Comment by chuckbutler** [comment]
Closed with #26
