### ISSUE TITLE
doc: README doesn't talk about changed etcdctl path after deb→snap migration

### ISSUE THREAD

**Issue by fghaas** [juju-solutions/layer-etcd#92]
When installing etcd from Debian packages, the `etcdctl` binary is simply `etcdctl`. Post snap migration, it's `etcd.etcdctl`. This breaks any existing tooling or scripts that used just `etcdctl`. The README might want to mention that.

**Comment by mbruzek** [comment]
@fghaas thank you for reporting this issue. Snapcraft has the notion of aliases where we can alias the old command to the new snap binary. That does not seem to be the case for etcd 2.3.8 so we will have to add code to get this working. The snap repository is here: https://github.com/markshuttle/etcd-snaps if you want to create an issue or submit a patch that would be most welcome.

**Comment by fghaas** [comment]
Hmm. Isn't that what https://github.com/markshuttle/etcd-snaps/commit/3f34d775da6e2aa96418771ab9e32fab1ea1a71a is already doing? Does the charm install an outdated snap?

**Comment by mbruzek** [comment]
For upgrade compatibility we were forced to use version 2.3.8 of etcd so we could migrate the 2.x etcd data for existing customers. We plan to use etcd 3.x in upcoming releases but this requires extra data transforms that we were not comfortable doing with the other things going into 1.6 release. We could make the same change to the 2.3.8 but there also is a command on the host that needs to be run to enable aliases that is outlined here: https://insights.ubuntu.com/2017/01/28/ubuntu-core-how-to-enable-aliases-for-your-snaps-commands/

**Comment by marcoceppi** [comment]
It's not that it's an old snap, it's that snap declaration for 2.3 and 3.0 don't have the alias declaration. We'll get that updated in the snapcraft for etcd so it's consistent.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809380.
