### ISSUE TITLE
Support/encpsulate the new backup format

### ISSUE THREAD

**Issue by lazypower** [juju-solutions/layer-etcd#94]
As outlined in [Disaster Recovery](https://coreos.com/etcd/docs/latest/v2/admin_guide.html) there is an etcdctl backup command. This should be used in favor of the tarball restoration method. 

Its reasonable to deprecate the original tarball, however care should be taken to support both. Perhaps keep `snapshot` and enable `backup` as another action, and note the `snapshot` action is deprecated in the action description.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809381.
